language: r
sudo: required
warnings_are_errors: false

r_binary_packages:
  - Rcpp
  - testthat
  
# System dependencies for rgdal and V8
apt_packages:
  - libgeos-dev
  - libgdal1-dev 
  - libproj-dev
  - libv8-dev
  - libgdal-dev # other packages from here
  
# Install development package
r_github_packages:
  - skgrange/threadr
