language: r
sudo: required
warnings_are_errors: false
cache: packages

r_packages:
  - devtools
  
# System dependencies for rgdal and V8
apt_packages:
  - libgeos-dev
  - libgdal1-dev 
  - libproj-dev
  - libv8-dev
  - libgdal-dev # other packages from here
  - libhdf5-serial-dev
  
# Install development package
r_github_packages:
  - skgrange/threadr

